import { ConstType } from '../utils';
import {
    CasterModuleKey,
    DefenderModuleKey,
    GuardModuleKey,
    MedicModuleKey,
    ModuleKey,
    SniperModuleKey,
    SpecialistModuleKey,
    SupporterModuleKey,
    VanguardModuleKey,
} from './moduleDef';
import { RoleKey } from './rolekey';
import { RoleTypeKey } from './roletypeDef';

export type RoleStar = 1 | 2 | 3 | 4 | 5 | 6;

export type RoleBasicInfo = Readonly<{
    star: RoleStar;
    type: RoleTypeKey;
    module: ModuleKey;
}>;

type SpecificRoleTypeBasicInfo<T extends RoleTypeKey, M extends ModuleKey> = Partial<
    Record<RoleKey, Readonly<{ star: RoleStar; module: M; type: T }>>
>;

const vanguardBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'vanguard', VanguardModuleKey>>()({
    Bagpipe: { star: 6, module: 'charger', type: 'vanguard' },
    Siege: { star: 6, module: 'pioneer', type: 'vanguard' },
    Saga: { star: 6, module: 'pioneer', type: 'vanguard' },
    Saileach: { star: 6, module: 'bearer', type: 'vanguard' },
    Flametail: { star: 6, module: 'pioneer', type: 'vanguard' },
    Vigil: { star: 6, module: 'tactician', type: 'vanguard' },
    Zima: { star: 5, module: 'pioneer', type: 'vanguard' },
    Texas: { star: 5, module: 'pioneer', type: 'vanguard' },
    Grani: { star: 5, module: 'charger', type: 'vanguard' },
    Reed: { star: 5, module: 'charger', type: 'vanguard' },
    Elysium: { star: 5, module: 'bearer', type: 'vanguard' },
    Chiave: { star: 5, module: 'pioneer', type: 'vanguard' },
    Wildmane: { star: 5, module: 'charger', type: 'vanguard' },
    Blacknight: { star: 5, module: 'tactician', type: 'vanguard' },
    Cantabile: { star: 5, module: 'agent', type: 'vanguard' },
    Puzzle: { star: 5, module: 'agent', type: 'vanguard' },
    Courier: { star: 4, module: 'pioneer', type: 'vanguard' },
    Scavenger: { star: 4, module: 'pioneer', type: 'vanguard' },
    Vigna: { star: 4, module: 'charger', type: 'vanguard' },
    Myrtle: { star: 4, module: 'bearer', type: 'vanguard' },
    Beanstalk: { star: 4, module: 'tactician', type: 'vanguard' },
    Fang: { star: 3, module: 'pioneer', type: 'vanguard' },
    Vanilla: { star: 3, module: 'pioneer', type: 'vanguard' },
    Plume: { star: 3, module: 'charger', type: 'vanguard' },
    Yato: { star: 2, module: 'pioneer', type: 'vanguard' },
});

const sniperBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'sniper', SniperModuleKey>>()({
    Exusiai: { star: 6, module: 'marksman', type: 'sniper' },
    Schwarz: { star: 6, module: 'heavyshooter', type: 'sniper' },
    W: { star: 6, module: 'artilleryman', type: 'sniper' },
    Poca: { star: 6, module: 'besieger', type: 'sniper' },
    Rosmontis: { star: 6, module: 'flinger', type: 'sniper' },
    Archetto: { star: 6, module: 'marksman', type: 'sniper' },
    Ash: { star: 6, module: 'marksman', type: 'sniper' },
    Chen_the_holungday: { star: 6, module: 'spreadshooter', type: 'sniper' },
    Fartooth: { star: 6, module: 'deadeye', type: 'sniper' },
    Fiammetta: { star: 6, module: 'artilleryman', type: 'sniper' },
    Snowstorm: { star: 6, module: 'heavyshooter', type: 'sniper' },
    Bluepoison: { star: 5, module: 'marksman', type: 'sniper' },
    Platinum: { star: 5, module: 'marksman', type: 'sniper' },
    Meteorite: { star: 5, module: 'artilleryman', type: 'sniper' },
    Provence: { star: 5, module: 'heavyshooter', type: 'sniper' },
    Firewatch: { star: 5, module: 'deadeye', type: 'sniper' },
    Executor: { star: 5, module: 'spreadshooter', type: 'sniper' },
    Greythroat: { star: 5, module: 'marksman', type: 'sniper' },
    Sesa: { star: 5, module: 'artilleryman', type: 'sniper' },
    Andreana: { star: 5, module: 'deadeye', type: 'sniper' },
    April: { star: 5, module: 'marksman', type: 'sniper' },
    Aosta: { star: 5, module: 'spreadshooter', type: 'sniper' },
    Toddifons: { star: 5, module: 'besieger', type: 'sniper' },
    Kroos_the_keen_glint: { star: 5, module: 'marksman', type: 'sniper' },
    Erato: { star: 5, module: 'besieger', type: 'sniper' },
    Greyy_the_lightningbearer: { star: 5, module: 'flinger', type: 'sniper' },
    Lunacub: { star: 5, module: 'deadeye', type: 'sniper' },
    Jessica: { star: 4, module: 'marksman', type: 'sniper' },
    Meteor: { star: 4, module: 'marksman', type: 'sniper' },
    Shirayuki: { star: 4, module: 'artilleryman', type: 'sniper' },
    Vermeil: { star: 4, module: 'marksman', type: 'sniper' },
    May: { star: 4, module: 'marksman', type: 'sniper' },
    Ambriel: { star: 4, module: 'deadeye', type: 'sniper' },
    Aciddrop: { star: 4, module: 'heavyshooter', type: 'sniper' },
    Pinecone: { star: 4, module: 'spreadshooter', type: 'sniper' },
    Totter: { star: 4, module: 'besieger', type: 'sniper' },
    Kroos: { star: 3, module: 'marksman', type: 'sniper' },
    Adnachiel: { star: 3, module: 'marksman', type: 'sniper' },
    Catapult: { star: 3, module: 'artilleryman', type: 'sniper' },
    Rangers: { star: 2, module: 'marksman', type: 'sniper' },
    Justiceknight: { star: 1, module: 'marksman', type: 'sniper' },
});

const medicBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'medic', MedicModuleKey>>()({
    Shining: { star: 6, module: 'medic', type: 'medic' },
    Nightingale: { star: 6, module: 'multitarget', type: 'medic' },
    Kaltsit: { star: 6, module: 'medic', type: 'medic' },
    Lumen: { star: 6, module: 'therapist', type: 'medic' },
    Reed_the_flame_shadow: { star: 6, module: 'incantation', type: 'medic' },
    Ptilopsis: { star: 5, module: 'multitarget', type: 'medic' },
    Silence: { star: 5, module: 'medic', type: 'medic' },
    Warfarin: { star: 5, module: 'medic', type: 'medic' },
    Ceylon: { star: 5, module: 'therapist', type: 'medic' },
    Breeze: { star: 5, module: 'multitarget', type: 'medic' },
    Folinic: { star: 5, module: 'medic', type: 'medic' },
    Whisperain: { star: 5, module: 'therapist', type: 'medic' },
    Tuye: { star: 5, module: 'medic', type: 'medic' },
    Mulberry: { star: 5, module: 'wandering', type: 'medic' },
    Honeyberry: { star: 5, module: 'wandering', type: 'medic' },
    Hibiscus_the_purifier: { star: 5, module: 'incantation', type: 'medic' },
    Paprika: { star: 5, module: 'chainheal', type: 'medic' },
    Myrrh: { star: 4, module: 'medic', type: 'medic' },
    Gavial: { star: 4, module: 'medic', type: 'medic' },
    Perfumer: { star: 4, module: 'multitarget', type: 'medic' },
    Sussurro: { star: 4, module: 'medic', type: 'medic' },
    Purestream: { star: 4, module: 'therapist', type: 'medic' },
    Chestnut: { star: 4, module: 'wandering', type: 'medic' },
    Hibiscus: { star: 3, module: 'medic', type: 'medic' },
    Ansel: { star: 3, module: 'medic', type: 'medic' },
    Lancet2: { star: 1, module: 'medic', type: 'medic' },
});

const casterBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'caster', CasterModuleKey>>()({
    Ifrit: { star: 6, module: 'blast', type: 'caster' },
    Eyjafjalla: { star: 6, module: 'core', type: 'caster' },
    Mostima: { star: 6, module: 'splash', type: 'caster' },
    Ceobe: { star: 6, module: 'core', type: 'caster' },
    Dusk: { star: 6, module: 'splash', type: 'caster' },
    Passenger: { star: 6, module: 'chain', type: 'caster' },
    Carnelian: { star: 6, module: 'phalanx', type: 'caster' },
    Goldenglow: { star: 6, module: 'mechaccord', type: 'caster' },
    Ebenholz: { star: 6, module: 'mystic', type: 'caster' },
    Amiya: { star: 5, module: 'core', type: 'caster' },
    Skyfire: { star: 5, module: 'splash', type: 'caster' },
    Nightmare: { star: 5, module: 'core', type: 'caster' },
    Leizi: { star: 5, module: 'chain', type: 'caster' },
    Absinthe: { star: 5, module: 'core', type: 'caster' },
    Leonhardt: { star: 5, module: 'splash', type: 'caster' },
    Beeswax: { star: 5, module: 'phalanx', type: 'caster' },
    Tomimi: { star: 5, module: 'core', type: 'caster' },
    Mint: { star: 5, module: 'phalanx', type: 'caster' },
    Iris: { star: 5, module: 'mystic', type: 'caster' },
    Lava_the_purgatory: { star: 5, module: 'splash', type: 'caster' },
    Corroserum: { star: 5, module: 'blast', type: 'caster' },
    Kjera: { star: 5, module: 'mechaccord', type: 'caster' },
    Rockrock: { star: 5, module: 'mechaccord', type: 'caster' },
    Astgenne: { star: 5, module: 'chain', type: 'caster' },
    Minimalist: { star: 5, module: 'mechaccord', type: 'caster' },
    Qanipalaat: { star: 5, module: 'core', type: 'caster' },
    Harmonie: { star: 5, module: 'mystic', type: 'caster' },
    Haze: { star: 4, module: 'core', type: 'caster' },
    Gitano: { star: 4, module: 'splash', type: 'caster' },
    Greyy: { star: 4, module: 'splash', type: 'caster' },
    Click: { star: 4, module: 'mechaccord', type: 'caster' },
    Indigo: { star: 4, module: 'mystic', type: 'caster' },
    Pudding: { star: 4, module: 'chain', type: 'caster' },
    Lava: { star: 3, module: 'splash', type: 'caster' },
    Steward: { star: 3, module: 'core', type: 'caster' },
    Durin: { star: 2, module: 'core', type: 'caster' },
    F12: { star: 2, module: 'splash', type: 'caster' },
});

const guardBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'guard', GuardModuleKey>>()({
    Silverash: { star: 6, module: 'lord', type: 'guard' },
    Skadi: { star: 6, module: 'dreadnought', type: 'guard' },
    Chen: { star: 6, module: 'swordmaster', type: 'guard' },
    Hellagur: { star: 6, module: 'musha', type: 'guard' },
    Blaze: { star: 6, module: 'centurion', type: 'guard' },
    Thorns: { star: 6, module: 'lord', type: 'guard' },
    Surtr: { star: 6, module: 'artsfighter', type: 'guard' },
    Mountain: { star: 6, module: 'fighter', type: 'guard' },
    Pallas: { star: 6, module: 'instructor', type: 'guard' },
    Nearl_the_radiant_knight: { star: 6, module: 'dreadnought', type: 'guard' },
    Irene: { star: 6, module: 'swordmaster', type: 'guard' },
    Gavial_the_invincible: { star: 6, module: 'centurion', type: 'guard' },
    Mlynar: { star: 6, module: 'liberator', type: 'guard' },
    Franka: { star: 6, module: 'dreadnought', type: 'guard' },
    Indra: { star: 5, module: 'fighter', type: 'guard' },
    Lappland: { star: 5, module: 'lord', type: 'guard' },
    Specter: { star: 5, module: 'centurion', type: 'guard' },
    Savage: { star: 5, module: 'centurion', type: 'guard' },
    Swire: { star: 5, module: 'instructor', type: 'guard' },
    Astesia: { star: 5, module: 'artsfighter', type: 'guard' },
    Flamebringer: { star: 5, module: 'dreadnought', type: 'guard' },
    Broca: { star: 5, module: 'centurion', type: 'guard' },
    Bibeak: { star: 5, module: 'swordmaster', type: 'guard' },
    Sideroca: { star: 5, module: 'artsfighter', type: 'guard' },
    Ayerscarpe: { star: 5, module: 'lord', type: 'guard' },
    Flint: { star: 5, module: 'fighter', type: 'guard' },
    Whislash: { star: 5, module: 'instructor', type: 'guard' },
    Guardamiya: { star: 5, module: 'artsfighter', type: 'guard' },
    Tachanka: { star: 5, module: 'swordmaster', type: 'guard' },
    Akafuyu: { star: 5, module: 'musha', type: 'guard' },
    Tequila: { star: 5, module: 'liberator', type: 'guard' },
    Lapluma: { star: 5, module: 'reaper', type: 'guard' },
    Highmore: { star: 5, module: 'reaper', type: 'guard' },
    Dagda: { star: 5, module: 'fighter', type: 'guard' },
    Dobermann: { star: 4, module: 'instructor', type: 'guard' },
    Matoimaru: { star: 4, module: 'dreadnought', type: 'guard' },
    Frostleaf: { star: 4, module: 'lord', type: 'guard' },
    Estelle: { star: 4, module: 'centurion', type: 'guard' },
    Mousse: { star: 4, module: 'artsfighter', type: 'guard' },
    Beehunter: { star: 4, module: 'fighter', type: 'guard' },
    Utage: { star: 4, module: 'musha', type: 'guard' },
    Conviction: { star: 4, module: 'dreadnought', type: 'guard' },
    Cutter: { star: 4, module: 'swordmaster', type: 'guard' },
    Arene: { star: 4, module: 'lord', type: 'guard' },
    Jackie: { star: 4, module: 'fighter', type: 'guard' },
    Luoxiaohei: { star: 4, module: 'lord', type: 'guard' },
    Quartz: { star: 4, module: 'heavysword', type: 'guard' },
    Melantha: { star: 3, module: 'dreadnought', type: 'guard' },
    Midnight: { star: 3, module: 'lord', type: 'guard' },
    Popukar: { star: 3, module: 'centurion', type: 'guard' },
    Castle3: { star: 1, module: 'dreadnought', type: 'guard' },
});

const defenderBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'defender', DefenderModuleKey>>()({
    Hoshiguma: { star: 6, module: 'protector', type: 'defender' },
    Saria: { star: 6, module: 'guardian', type: 'defender' },
    Nian: { star: 6, module: 'protector', type: 'defender' },
    Eunectes: { star: 6, module: 'duelist', type: 'defender' },
    Blemishine: { star: 6, module: 'guardian', type: 'defender' },
    Mudrock: { star: 6, module: 'juggernaut', type: 'defender' },
    Horn: { star: 6, module: 'fortress', type: 'defender' },
    Penance: { star: 6, module: 'juggernaut', type: 'defender' },
    Nearl: { star: 5, module: 'guardian', type: 'defender' },
    Liskarm: { star: 5, module: 'sentry', type: 'defender' },
    Croissant: { star: 5, module: 'protector', type: 'defender' },
    Vulcan: { star: 5, module: 'juggernaut', type: 'defender' },
    Bison: { star: 5, module: 'protector', type: 'defender' },
    Hung: { star: 5, module: 'guardian', type: 'defender' },
    Asbestos: { star: 5, module: 'artsprotector', type: 'defender' },
    Blitz: { star: 5, module: 'sentry', type: 'defender' },
    Heavyrain: { star: 5, module: 'protector', type: 'defender' },
    Ashlock: { star: 5, module: 'fortress', type: 'defender' },
    Aurora: { star: 5, module: 'duelist', type: 'defender' },
    Shalem: { star: 5, module: 'artsprotector', type: 'defender' },
    Czerny: { star: 5, module: 'artsprotector', type: 'defender' },
    Matterhorn: { star: 5, module: 'protector', type: 'defender' },
    Cuora: { star: 4, module: 'protector', type: 'defender' },
    Gummy: { star: 4, module: 'guardian', type: 'defender' },
    Durnar: { star: 4, module: 'artsprotector', type: 'defender' },
    Bubble: { star: 4, module: 'protector', type: 'defender' },
    Cardigan: { star: 3, module: 'protector', type: 'defender' },
    Beagle: { star: 3, module: 'protector', type: 'defender' },
    Spot: { star: 3, module: 'guardian', type: 'defender' },
    Noircorne: { star: 2, module: 'protector', type: 'defender' },
});

const supporterBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'supporter', SupporterModuleKey>>()({
    Angelina: { star: 6, module: 'decelbinder', type: 'supporter' },
    Magallan: { star: 6, module: 'summoner', type: 'supporter' },
    Suzuran: { star: 6, module: 'decelbinder', type: 'supporter' },
    Skadi_the_corrupting_heart: { star: 6, module: 'bard', type: 'supporter' },
    Gnosis: { star: 6, module: 'hexer', type: 'supporter' },
    Ling: { star: 6, module: 'summoner', type: 'supporter' },
    Stainless: { star: 6, module: 'artificer', type: 'supporter' },
    Mayer: { star: 5, module: 'summoner', type: 'supporter' },
    Pramanix: { star: 5, module: 'hexer', type: 'supporter' },
    Istina: { star: 5, module: 'decelbinder', type: 'supporter' },
    Sora: { star: 5, module: 'bard', type: 'supporter' },
    Glaucus: { star: 5, module: 'decelbinder', type: 'supporter' },
    Shamare: { star: 5, module: 'hexer', type: 'supporter' },
    Tsukinogi: { star: 5, module: 'abjurer', type: 'supporter' },
    Scene: { star: 5, module: 'summoner', type: 'supporter' },
    Ninecoloreddeer: { star: 5, module: 'abjurer', type: 'supporter' },
    Quercus: { star: 5, module: 'abjurer', type: 'supporter' },
    Heidi: { star: 5, module: 'bard', type: 'supporter' },
    Windflit: { star: 5, module: 'artificer', type: 'supporter' },
    Proviso: { star: 5, module: 'decelbinder', type: 'supporter' },
    Deepcolor: { star: 4, module: 'summoner', type: 'supporter' },
    Earthspirit: { star: 4, module: 'decelbinder', type: 'supporter' },
    Podenco: { star: 4, module: 'decelbinder', type: 'supporter' },
    Roberta: { star: 4, module: 'artificer', type: 'supporter' },
    Orchid: { star: 3, module: 'decelbinder', type: 'supporter' },
});

const specialistBasicInfo = ConstType<SpecificRoleTypeBasicInfo<'specialist', SpecialistModuleKey>>()({
    Aak: { star: 6, module: 'geek', type: 'specialist' },
    Phantom: { star: 6, module: 'executor', type: 'specialist' },
    Weedy: { star: 6, module: 'pushstroker', type: 'specialist' },
    Gladiia: { star: 6, module: 'hookmaster', type: 'specialist' },
    Mizuki: { star: 6, module: 'ambusher', type: 'specialist' },
    Lee: { star: 6, module: 'merchant', type: 'specialist' },
    Specter_the_unchained: { star: 6, module: 'dollkeeper', type: 'specialist' },
    Dorothy: { star: 6, module: 'trapmaster', type: 'specialist' },
    Texas_the_omertosa: { star: 6, module: 'executor', type: 'specialist' },
    Projektred: { star: 5, module: 'executor', type: 'specialist' },
    Cliffheart: { star: 5, module: 'hookmaster', type: 'specialist' },
    Manticore: { star: 5, module: 'ambusher', type: 'specialist' },
    Feater: { star: 5, module: 'pushstroker', type: 'specialist' },
    Waaifu: { star: 5, module: 'executor', type: 'specialist' },
    Snowsant: { star: 5, module: 'hookmaster', type: 'specialist' },
    Robin: { star: 5, module: 'trapmaster', type: 'specialist' },
    Kafka: { star: 5, module: 'executor', type: 'specialist' },
    Mrnothing: { star: 5, module: 'merchant', type: 'specialist' },
    Frost: { star: 5, module: 'trapmaster', type: 'specialist' },
    Bena: { star: 5, module: 'dollkeeper', type: 'specialist' },
    Kirara: { star: 5, module: 'ambusher', type: 'specialist' },
    Enforcer: { star: 5, module: 'pushstroker', type: 'specialist' },
    Kazemaru: { star: 5, module: 'dollkeeper', type: 'specialist' },
    Gravel: { star: 4, module: 'executor', type: 'specialist' },
    Rope: { star: 4, module: 'hookmaster', type: 'specialist' },
    Shaw: { star: 4, module: 'pushstroker', type: 'specialist' },
    Ethan: { star: 4, module: 'ambusher', type: 'specialist' },
    Jaye: { star: 4, module: 'merchant', type: 'specialist' },
    Thermalex: { star: 1, module: 'executor', type: 'specialist' },
});

/**幹員基本資訊 */
export const roleBasicInfo: Readonly<Record<RoleKey, RoleBasicInfo>> = Object.freeze({
    ...vanguardBasicInfo,
    ...sniperBasicInfo,
    ...medicBasicInfo,
    ...casterBasicInfo,
    ...guardBasicInfo,
    ...defenderBasicInfo,
    ...supporterBasicInfo,
    ...specialistBasicInfo,
});
